Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "forwarded_port", guest: 8085, host: 8085

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.linked_clone = true
  end

  config.vm.define "test1" do |srv|
    srv.vm.hostname = "test1"
    srv.vm.network "private_network", type: "dhcp"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
#    ansible.force_remote_user = true
#    ansible.extra_vars = { init_db: true }
  end
end
